#!/bin/bash

TABLES=$(bq ls --max_results 10000 pipeline_classify  | grep TABLE | pyin 'line.strip().split()[0]' | head -2)

for T in ${TABLES}; do
    echo bq -q cp pipeline_classify.${T} ucsb-gfw:pipeline_classify.${T}
done | parallel -j 16 
